-- Listでパラメータ指定した場合
TEST_IN_CONDITION_WITH_LIST =
SELECT
  *
FROM
  CACHE_STATEMENT_TEST_TABLE
WHERE
  COL_NAME_1 IN (:list[]) ORDER BY COL_NAME_1

-- Mapでパラメータ指定した場合
TEST_IN_CONDITION_WITH_MAP =
SELECT
  *
FROM
  CACHE_STATEMENT_TEST_TABLE
WHERE
  COL_NAME_1 IN (:map[]) ORDER BY COL_NAME_1

-- 配列でパラメータ指定した場合
-- ページングを使用した場合
TEST_IN_CONDITION_WITH_ARRAY =
SELECT
  *
FROM
  CACHE_STATEMENT_TEST_TABLE
WHERE
  COL_NAME_1 IN (:array[]) ORDER BY COL_NAME_1

-- SQLにパラメータの添え字を指定した場合
TEST_IN_CONDITION_WRITE_ARRAY_INDEX =
SELECT
  *
FROM
  CACHE_STATEMENT_TEST_TABLE
WHERE
  COL_NAME_1 IN (:array[0], :array[1]) ORDER BY COL_NAME_1

-- ソートを行う場合
TEST_IN_CONDITION_DO_SORT =
SELECT
  *
FROM
  CACHE_STATEMENT_TEST_TABLE
WHERE
  COL_NAME_1 IN (:array[])
$sort(sortId){
  (col_name1_asc COL_NAME_1 asc)
  (col_name1_desc COL_NAME_1 desc)
}

